version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - public-network
      - internal-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
    command: bash -c "node ./src/scripts/populate.js && npm start"


  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - internal-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal-network

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=86400  # 24h
    networks:
      - internal-network

volumes:
  mongo-data:

networks:
  public-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true