version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/travelDestinations
    depends_on:
      - mongo
    networks:
      - public-network
      - internal-network
    command: bash -c "node ./src/scripts/populate.js && npm start"


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - internal-network

volumes:
  mongo-data:

networks:
  public-network:
    driver: bridge
  internal-network:
    driver: bridge